// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuoT27ccenpl0thnjRPXsuLKx4DwNpAw',
    appId: '1:439008963840:web:dec5484c92990775c617e5',
    messagingSenderId: '439008963840',
    projectId: 'pengaduansamsat',
    authDomain: 'pengaduansamsat.firebaseapp.com',
    storageBucket: 'pengaduansamsat.firebasestorage.app',
    measurementId: 'G-WZBMG0E5YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-nZbXedECi81bHhIbHNivY9Fw1LzZEU',
    appId: '1:439008963840:android:e9978f607ab15df3c617e5',
    messagingSenderId: '439008963840',
    projectId: 'pengaduansamsat',
    storageBucket: 'pengaduansamsat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX3XSU1oH7ZdcvLbKD9GH-O4QCBpNgSCY',
    appId: '1:439008963840:ios:6cbc14b1bdd23b2cc617e5',
    messagingSenderId: '439008963840',
    projectId: 'pengaduansamsat',
    storageBucket: 'pengaduansamsat.firebasestorage.app',
    iosBundleId: 'com.example.aplikasipengaduansamsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX3XSU1oH7ZdcvLbKD9GH-O4QCBpNgSCY',
    appId: '1:439008963840:ios:6cbc14b1bdd23b2cc617e5',
    messagingSenderId: '439008963840',
    projectId: 'pengaduansamsat',
    storageBucket: 'pengaduansamsat.firebasestorage.app',
    iosBundleId: 'com.example.aplikasipengaduansamsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhuoT27ccenpl0thnjRPXsuLKx4DwNpAw',
    appId: '1:439008963840:web:1b77145663d7705ac617e5',
    messagingSenderId: '439008963840',
    projectId: 'pengaduansamsat',
    authDomain: 'pengaduansamsat.firebaseapp.com',
    storageBucket: 'pengaduansamsat.firebasestorage.app',
    measurementId: 'G-QGKQ78W17K',
  );
}
